"""
scripts/01_env_setup.py
========================
PHASE 2 — Environment Verification & Package Installation

Checks:
  - Python version (≥3.8)
  - pip
  - CUDA availability
  - PyTorch + CUDA version
  - Ultralytics YOLOv8
  - GPU name, VRAM, driver
  - OpenCV
  - Required packages

Installs missing packages automatically.
Writes reports/env_report.md.
"""

from __future__ import annotations

import subprocess
import sys
import platform
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
REPORTS_DIR  = PROJECT_ROOT / "reports"


def run(cmd: str) -> tuple[str, str, int]:
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return r.stdout.strip(), r.stderr.strip(), r.returncode


def title(s: str) -> None:
    print(f"\n{'─'*60}\n  {s}\n{'─'*60}")


def ok(s: str)   -> None: print(f"  ✅  {s}")
def warn(s: str) -> None: print(f"  ⚠️   {s}")
def err(s: str)  -> None: print(f"  ❌  {s}")


def check_python() -> None:
    title("Python")
    v = sys.version_info
    print(f"  Version : {sys.version}")
    print(f"  Path    : {sys.executable}")
    (ok if (v.major == 3 and v.minor >= 8) else err)(f"Python {v.major}.{v.minor}")


def install_if_missing(pkg: str, import_name: str | None = None) -> None:
    name = import_name or pkg.split("==")[0].replace("-", "_")
    try:
        __import__(name)
        ok(f"{pkg} installed")
    except ImportError:
        warn(f"{pkg} missing — installing...")
        out, serr, code = run(f"{sys.executable} -m pip install {pkg} -q")
        if code == 0:
            ok(f"{pkg} installed successfully")
        else:
            err(f"Failed to install {pkg}: {serr[:200]}")


def check_torch_cuda() -> dict:
    title("PyTorch + CUDA")
    info: dict = {}
    try:
        import torch
        ok(f"PyTorch {torch.__version__}")
        info["torch_version"] = torch.__version__
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            vram     = torch.cuda.get_device_properties(0).total_memory / 1e9
            ok(f"CUDA available ✓  —  GPU: {gpu_name}  ({vram:.1f} GB VRAM)")
            ok(f"CUDA version: {torch.version.cuda}")
            info.update(cuda=True, gpu=gpu_name, vram_gb=round(vram, 1),
                        cuda_version=torch.version.cuda)
        else:
            warn("CUDA not available — training will use CPU (slow)")
            info["cuda"] = False
    except ImportError:
        err("PyTorch not installed — installing...")
        run(f"{sys.executable} -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118 -q")
        info["torch_version"] = "just-installed"
    return info


def check_ultralytics() -> None:
    title("Ultralytics YOLOv8")
    try:
        import ultralytics
        ok(f"ultralytics {ultralytics.__version__}")
    except ImportError:
        warn("ultralytics missing — installing...")
        out, serr, code = run(f"{sys.executable} -m pip install ultralytics -q")
        (ok if code == 0 else err)(f"ultralytics install {'done' if code==0 else 'FAILED'}")


def check_packages() -> None:
    title("Required Packages")
    packages = [
        ("pillow",       "PIL"),
        ("pyyaml",       "yaml"),
        ("tqdm",         "tqdm"),
        ("matplotlib",   "matplotlib"),
        ("seaborn",      "seaborn"),
        ("opencv-python","cv2"),
        ("pandas",       "pandas"),
        ("numpy",        "numpy"),
        ("scipy",        "scipy"),
        ("scikit-learn", "sklearn"),
    ]
    for pkg, imp in packages:
        install_if_missing(pkg, imp)


def check_gpu_driver() -> None:
    title("GPU Driver (nvidia-smi)")
    out, serr, code = run("nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader")
    if code == 0:
        ok(f"nvidia-smi: {out}")
    else:
        warn("nvidia-smi not found or no NVIDIA GPU detected")


def write_report(torch_info: dict) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Environment Report — NXP Cup India 2026",
        "",
        f"| Item | Value |",
        f"|------|-------|",
        f"| OS | {platform.platform()} |",
        f"| Python | {sys.version.split()[0]} |",
        f"| PyTorch | {torch_info.get('torch_version', 'N/A')} |",
        f"| CUDA | {torch_info.get('cuda_version', 'N/A')} |",
        f"| GPU | {torch_info.get('gpu', 'CPU only')} |",
        f"| VRAM | {torch_info.get('vram_gb', 'N/A')} GB |",
        "",
        "*Generated by 01_env_setup.py*",
    ]
    (REPORTS_DIR / "env_report.md").write_text("\n".join(lines))
    print(f"\n  📄 Report saved → {REPORTS_DIR / 'env_report.md'}")


def main() -> None:
    print("\n" + "═"*60)
    print("  PHASE 2 — Environment Verification")
    print("═"*60)

    check_python()
    check_gpu_driver()
    torch_info = check_torch_cuda()
    check_ultralytics()
    check_packages()
    write_report(torch_info)

    print("\n" + "═"*60)
    print("  Environment check complete. Proceeding to Phase 3...")
    print("═"*60 + "\n")


if __name__ == "__main__":
    main()
